# Generated by Django 3.1.4 on 2020-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
