# Generated by Django 3.1.5 on 2021-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_collaborativelist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=128)),
                ('datetime', models.CharField(default='none', max_length=128)),
                ('address', models.CharField(default='none', max_length=128)),
                ('lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=15)),
            ],
        ),
    ]
